export const vehiculos = [
  {
    fecha: '10/10/2021',
    patente: 'AD004WU',
    filtroAceite: 'Filtro',
    filtroAire: 'Filtro aire',
    filtroCombustible: 'Filtro combustible',
    liquidoEmbrague: 'Liquido de embrague',
    liquidoFrenos: 'Liquido de frenos',
    pastillasFrenos: 'Pastillas de frenos',
    correa: 'Correa',
    correaDistribucion: 'Correa Distribuicion',
    refrigerante: 'Refrigerante',
  },
  {
    fecha: '6/06/2021',
    patente: 'AE941VW',
    filtroAceite: 'Filtro',
    filtroAire: 'Filtro aire',
    filtroCombustible: 'Filtro combustible',
    liquidoEmbrague: 'Liquido de embrague',
    liquidoFrenos: 'Liquido de frenos',
    pastillasFrenos: 'Pastillas de frenos',
    correa: 'Correa',
    correaDistribucion: 'Correa Distribuicion',
    refrigerante: 'Refrigerante',
  },
];
